# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: '9JIaLOUpEf8Lik7GtsnPy3wFY'
  twitter_api_secret: 'oihXKmdDRR2EWuAyObwlmCPwY6AiC5FqKtpLvs57gdHJ00vRgO'


development:
  secret_key_base: 5a5aa8f85aede829c153dc04a4a583d4444d1f9c6669cf3e3c3bb34ffa0e11ec5cfc386439cb9de66a40f66f091b5474c022d0576f32e6e31035fe5f6f20bcd1
  <<: *default_twitter


test:
  secret_key_base: 7cd7e6239b926f4ee05d8a7541c5d77358ac9f3993bc8eb1955b48127f3b2229acefae3de9f5640b0462b0dd26aa5320a852f114589e8ddf60f7d28a24070946
  <<: *default_twitter


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>